let g:gruvbox_contrast_dark='hard'
colorscheme gruvbox

set background=dark
set t_Co=256
set synmaxcol=2048
"":set clipboard^=unnamed


" " Copy to clipboard
vnoremap  <leader>y  "+y
nnoremap  <leader>Y  "+yg_
nnoremap  <leader>y  "+y
nnoremap  <leader>yy  "+yy

" " Paste from clipboard
nnoremap <leader>p "+p
nnoremap <leader>P "+P
vnoremap <leader>p "+p
vnoremap <leader>P "+P


"f5 to execute
nnoremap <silent> <F5> :!python %<CR>
""colorscheme monokai


set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')


set visualbell



set pastetoggle=<F10>
""save with \s
noremap <Leader>s :update<CR>
" This is the Vundle package, which can be found on GitHub.
" For GitHub repos, you specify plugins using the
" 'user/repository' format
Plugin 'gmarik/vundle'

" We could also add repositories with a ".git" extension

" To get plugins from Vim Scripts, you can reference the plugin
" by name as it appears on the site
Plugin 'Buffergator'

Plugin 'scrooloose/nerdtree'
""F2 to open and close
map <F2> :NERDTreeToggle<CR>
map  <C-l> :tabn<CR>
map  <C-h> :tabp<CR>
map  <C-n> :tabnew<CR>
Bundle 'jistr/vim-nerdtree-tabs'

Plugin 'davidhalter/jedi-vim'
Plugin 'vim-syntastic/syntastic'
" Syntastic Configuration
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
:let g:syntastic_loc_list_height=5

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0
" let g:syntastic_enable_elixir_checker = 1
" let g:syntastic_elixir_checkers = ["elixir"]

Bundle 'klen/python-mode'
"" Python mode config
""Disable rope to avoid hanging
let g:pymode_rope = 0 
let g:pymode_options_colorcolumn = 0

Plugin 'easymotion/vim-easymotion'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'Townk/vim-autoclose'
Plugin 'universal-ctags/ctags'
Plugin 'majutsushi/tagbar'
""tagbar config
""map to F8
nmap <F8> :TagbarToggle<CR>


Plugin 'sheerun/vim-polyglot'
""Themes/Colourschemes
Plugin 'flazz/vim-colorschemes'
Plugin 'chriskempson/base16-vim'

Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'mileszs/ack.vim'
Plugin 'morhetz/gruvbox'
Plugin 'tpope/vim-fugitive'
Plugin 'nvie/vim-flake8'
Bundle 'vim-ruby/vim-ruby'


call vundle#end()            " required
filetype plugin indent on    " required
let g:AutoClosePreserveDotReg = 0
"""" END Vundle Configuration 


