set background=dark
set t_Co=256
set synmaxcol=2048
"":set clipboard^=unnamed


" " Copy to clipboard
vnoremap  <leader>y  "+y
nnoremap  <leader>Y  "+yg_
nnoremap  <leader>y  "+y
nnoremap  <leader>yy  "+yy

" " Paste from clipboard
nnoremap <leader>p "+p
nnoremap <leader>P "+P
vnoremap <leader>p "+p
vnoremap <leader>P "+P


"f5 to execute
nnoremap <silent> <F5> :!python %<CR>
colorscheme molokai
set nocompatible
""Vundle config start
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
set visualbell
set pastetoggle=<F10>
""save with \s
noremap <Leader>s :update<CR>
" This is the Vundle package, which can be found on GitHub.
" For GitHub repos, you specify plugins using the
" 'user/repository' format
Plugin 'gmarik/vundle'

" We could also add repositories with a ".git" extension

" To get plugins from Vim Scripts, you can reference the plugin
" by name as it appears on the site
Plugin 'Buffergator'

Plugin 'scrooloose/nerdtree'
""F2 to open and close
map <F2> :NERDTreeToggle<CR>
map  <C-l> :tabn<CR>
map  <C-h> :tabp<CR>
map  <C-n> :tabnew<CR>
Bundle 'jistr/vim-nerdtree-tabs'

Plugin 'valloric/YouCompleteMe'
""You complete me config
let g:ycm_collect_identifiers_from_tags_files = 1 " Let YCM read tags from Ctags file
let g:ycm_use_ultisnips_completer = 1 " Default 1, just ensure
let g:ycm_seed_identifiers_with_syntax = 1 " Completion for programming language's keyword
let g:ycm_complete_in_comments = 1 " Completion in comments
let g:ycm_complete_in_strings = 1 " Completion in string

let g:ycm_key_list_select_completion = ['<C-j>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-k>', '<Up>']
""Ensure preview window does not open
set completeopt-=preview
" Goto definition with F3
map <F3> :YcmCompleter GoTo<CR>


Plugin 'vim-syntastic/syntastic'
" Syntastic Configuration
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
:let g:syntastic_loc_list_height=5

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0
" let g:syntastic_enable_elixir_checker = 1
" let g:syntastic_elixir_checkers = ["elixir"]

Bundle 'klen/python-mode'
"" Python mode config
""Disable rope to avoid hanging
let g:pymode_rope = 0 
let g:pymode_options_colorcolumn = 0

Plugin 'easymotion/vim-easymotion'

Plugin 'Townk/vim-autoclose'
Plugin 'universal-ctags/ctags'
Plugin 'majutsushi/tagbar'
""tagbar config
""map to F8
nmap <F8> :TagbarToggle<CR>


Plugin 'sheerun/vim-polyglot'
""Themes/Colourschemes
Plugin 'flazz/vim-colorschemes'
Plugin 'ctrlpvim/ctrlp.vim'

call vundle#end()            " required
filetype plugin indent on    " required
let g:AutoClosePreserveDotReg = 0
"""" END Vundle Configuration 


